### ISSUE TITLE
Patent Items

### ISSUE THREAD

**Issue by libora** [avram/zotero-bits#56]
Is it posible to mapping somes Zotero fields to unused CSL fields?

------------------------------
attorneyAgent (in roles of patent´s aplicant creator/owner - maybe can be changed name of this field in Zotero or add new item) -> containerAuthor
fillingDate -> submitted
issuingAuthoritiy -> publisher
legalStatus -> status

------------------------------
For ISO 690 we need variables in CSL for country (or code of country) and official designation of the series. 

ISO Standard 690:2010(E), Information & Documentation - Guidelines for Bibliographic References and Citations to Information Resources, section 15.9 recommends patents be cited similar to a contribution within a journal.  The first element listed should be the name of the applicant creator, followed by the title of the patent.  The country name or code and the official designation of the series within which the patent resource is numbered should follow.  The patent serial number should suffice as numeration.

ISO examples:

Douglass, Elias B.  Cow Milker.  US Patent 361,213.  1887.

Philip Morris, Inc.  Optical Perforating Apparatus and System.  European patent application 0021165 A1.  1981-01-07.

Winget Ltd.  Detachable Bulldozer Attachment for Dumper Vehicles.  Inventor:  Reginald John England.  8 March 1967.  Appl: 10 June 1963.  Int. Cl: E02F 3/76.  GB Cl: E1F12.  GB Patent Specification 1060631.

**Comment by adam3smith** [comment]
we now have
fillingDate -> submitted
issuingAuthoritiy -> authority
legalStatus -> status
mapped. Closing this since I don't think we'll map the attorney field.
